main: com.elixiumnetwork.playerwarp.PWarpPlugin
name: PWarp
version: 7.2
api-version: 1.13
author: The_King_Senne
softdepend: [GriefPrevention, Vault]
commands:
  pwarp:
    description: Main command for playerwarps
    aliases: pw
    usage: "/pw help"
  pwg:
    description: Opens the warp GUI
    usage: "/pwg"
  pwarps:
    description: Opens the warp GUI
    aliases: pws
    usage: "/pwarps"
  pwwarp:
    description: Warps to a warp
    aliases: pww
    usage: "/pwwarp <warp>"

